version: "1"
services:
  db-postgres:
    image: postgres:14.5
    restart: unless-stopped
    container_name: cloud-video-storage-db
    volumes:
      - pgCvsData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment: 
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - default
volumes:
  pgCvsData: